### ISSUE TITLE
Missing billing information about LUMI-O

### ISSUE THREAD

**Issue by Chroxvi** [Lumi-supercomputer/lumi-userguide#134]
The [Storage Billing page](https://docs.lumi-supercomputer.eu/runjobs/lumi_env/billing/#storage-billing) does not mention the billing rate of LUMI-O storage. Rumor has it that LUMI-O is billed at ½ the rate of LUMI-P. This needs to be confirmed and added to the public LUMI docs.

**Comment by olouant** [comment]
Done in [1557661](https://github.com/Lumi-supercomputer/lumi-userguide/commit/155766168c2c4624cc601d2781315d0ffa71383f).
