### ISSUE TITLE
LUMI-C node count not up to date

### ISSUE THREAD

**Issue by Chroxvi** [Lumi-supercomputer/lumi-userguide#143]
The [LUMI-C docs page](https://docs.lumi-supercomputer.eu/hardware/lumic/) still only lists a total of 1536 LUMI-C nodes. Following the recent maintenance break, we should now have an additional 512 LUMI-C nodes for a total of 2048. The documentation should be updated to reflect this.

**Comment by olouant** [comment]
Done in [3e2c1d8](https://github.com/Lumi-supercomputer/lumi-userguide/commit/3e2c1d8ec0a2e82ec4d3af2a2e62eff89a532e99).
