### ISSUE TITLE
Update docs for conda-containerize

### ISSUE THREAD

**Issue by trz42** [Lumi-supercomputer/lumi-userguide#60]
If the `install_dir` used in

```bash
conda-containerize new --prefix <install_dir> env.yml
```

does not exist, the command returns an error. Should be clarified that this directory must exist. In the later "end-to-end" example on the page, the directory is created before `conda-containerize` is run. So, maybe simple fix could be to do that here too, e.g.,

```bash
mkdir myInstallDir
conda-rontainerize new --prefix myInstallDir env.yml
```

**Comment by Chroxvi** [comment]
The suggested change has been implemented in #127.
