### ISSUE TITLE
GitHub logo could bring here

### ISSUE THREAD

**Issue by MatiasJJ** [Lumi-supercomputer/lumi-userguide#73]
THe GitHub logo at the bottom of the [LUMI Docs](https://docs.lumi-supercomputer.eu/firststeps/getstarted/) could bring to this repo https://github.com/Lumi-supercomputer/lumi-userguide instead of https://github.com/Lumi-supercomputer/

**Comment by Danzelot** [comment]
Thank you for the suggestion.
